### ISSUE TITLE
Add MacOS targets, too

### ISSUE THREAD

**Issue by dgmltn** [chRyNaN/validator#1]
Is it possible to build this for the MacOS targets too?

```
:MultiPlatformLibrary:macosX64Main: Could not resolve com.chrynan.validator:validator-core:0.6.0.
:MultiPlatformLibrary:macosX64Test: Could not resolve com.chrynan.validator:validator-core:0.6.0.
```

**Comment by luca992** [comment]
+1 can all [tier 1-3](https://kotlinlang.org/docs/native-target-support.html) targets be added?

**Comment by OptimumCode** [comment]
Hi, @chRyNaN. Could you please advise if you could review a pull request to close this issue and publish the new library version after that?
I haven't seen any commits for the past year and I am wondering if this library is still alive. If it is not I would probably fork the repo and publish the library under a new group

**Comment by chRyNaN** [comment]
Mac, Linux, and WASM targets have been added in the latest version: https://github.com/chRyNaN/validator/releases/tag/0.7.0

**Comment by OptimumCode** [comment]
> Mac, Linux, and WASM targets have been added in the latest version: https://github.com/chRyNaN/validator/releases/tag/0.7.0

Hi, @chRyNaN. Thank you for finding time to make these changes. But it looks like there are some issues with authorization to the repository where you publish artifacts. Could you please take a look at it?

**Comment by chRyNaN** [comment]
@OptimumCode Could you elaborate on what issue are exactly facing? The repository should be public for retrieving artifacts. Can you download the metadata JSON file at the following link: https://repo.repsy.io/mvn/chrynan/public/com/chrynan/validator/validator-core/0.7.0/validator-core-0.7.0-kotlin-tooling-metadata.json

If you can see that, you should be able to access all of the binaries. Here's some potential solutions:

* Make sure to add the repository to your build file:
```kotlin
repositories {
    maven { url = uri("https://repo.repsy.io/mvn/chrynan/public") }
}
```

* There were breaking changes in the [latest release](https://github.com/chRyNaN/validator/releases/tag/0.7.0) and the coroutines module is no longer available as it has been merged with the core module.
* Make sure that you are using the correct version. The latest is `0.7.0`.
* If that doesn't work, please post the error log you are encountering.

**Comment by OptimumCode** [comment]
Thank you for your response @chRyNaN. I was talking about the GitHub workflow for Publication. I should have clarified this, sorry about that.
I have access to maven repository and can download artifacts - no issues there
